[tool.poetry]
name = "aitools_samagra"
version = "0.1.0"
description = "AI Tooling to bootstrap applications fast"
authors = ["Tushar <codingid6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
asyncio = "^3.4.3"
aiohttp = "^3.8.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
